language: python
python:
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install --upgrade pip
    - python setup.py -q install
    - pip install -r test_requirements.txt
script:
    - pytest
    #- flake8 grazyna/

